---
layout: post
title: (git memo) not have locally.エラーとaddのエスケープ # ページタイトル
tags: command git # タグ
categories: git # カテゴリ. AtCoderの解説記事は atcoder で.
published: true # ここは必ずtrueにしてください.
---


* TOC
{:toc}

Author: Non　<!-- 自分の名前 -->

<!-- ↓↓↓↓↓ 記事内容 ↓↓↓↓↓ -->

##  not have locally.エラー

今操作しているPCにコミットし忘れたデータがあり、急いでadd, commit, pushすると以下のようなエラーが起きる。

```
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

このエラーは現在、PC上のステージにあるデータをリモートリポジトリにPushしようしたら、ステージ上より新しいCommitが存在しているときに起こるエラーである。ので、一度ローカルにMaster上にある最新のデータをPullして、Mergeする必要がある。

手順は以下の通り。

1. `git checkout -b {適当なブランチ名}` # 新規にブランチを作成してmasterから新規のブランチに移動
2. `git pull origin master` # 新規のブランチにローカルにあるmasterをpull
3. `git add .` # ローカルデータをステージに上げる
4. `git commit -m "message"` # commit
5. `git push origin {新規に作成したブランチ}`
6. `git merge {新規に作成したブランチ} master` # 新規に作成したブランチをmasterにmerge
7. `git push origin master` # masterをローカルにpush

<br>

## 特定のファイルのgit addを取り消す

`git rm --cached {ファイル}`

フォルダの場合は
`git rm --cached {フォルダ}`

すべて取り消す場合は

`git rm --cached .`

[foobarpiyopiyo]:{{"/foo/bar/piyo/piyo"|prepend:site.url}}

